task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# Adjust to your IR data set
num_classes: 9
remap_mscoco_category: False

# ---------------------------------------------------------------------------
# TRAIN/VAL DATALOADERS
# ---------------------------------------------------------------------------
# These paths mirror the structure that `tools/prepare_ir_dataset.sh` creates:
#   /mnt/local/D-FINE/ir_datasets/ir_obj_det_coco
#   /mnt/local/D-FINE/ir_datasets/based_eval_coco
# If you keep a different layout, just change the four paths below.

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /mnt/local/D-FINE/ir_datasets/ir_obj_det_coco/images/train
    ann_file: /mnt/local/D-FINE/ir_datasets/ir_obj_det_coco/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        # Ensure that every input image is resized to 1280×1280 (the size expected by the
        # DFINE pre-trained checkpoints).  The fixed resolution guarantees that the cached
        # positional embeddings inside the HybridEncoder match the feature-map size and
        # prevents the size-mismatch error observed with 640×512 inputs.
        - {type: Resize, size: [1280, 1280]}
  shuffle: True
  num_workers: 2
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /mnt/local/D-FINE/ir_datasets/based_eval_coco/images/train
    ann_file: /mnt/local/D-FINE/ir_datasets/based_eval_coco/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [1280, 1280]}
  shuffle: False
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
