task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# Adjust to your IR data set
num_classes: 9
remap_mscoco_category: False

# ---------------------------------------------------------------------------
# TRAIN/VAL DATALOADERS
# ---------------------------------------------------------------------------
# These paths mirror the structure that `tools/prepare_ir_dataset.sh` creates:
#   /mnt/local/D-FINE/ir_datasets/ir_obj_det_coco
#   /mnt/local/D-FINE/ir_datasets/based_eval_coco
# If you keep a different layout, just change the four paths below.

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /mnt/local/D-FINE/ir_datasets/ir_obj_det_coco/images/train
    ann_file: /mnt/local/D-FINE/ir_datasets/ir_obj_det_coco/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 2
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /mnt/local/D-FINE/ir_datasets/based_eval_coco/images/train
    ann_file: /mnt/local/D-FINE/ir_datasets/based_eval_coco/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction

